name: Pipeline Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
        contents: read
        pages: write
        id-token: write
    environment:
        name: github-pages
        url: https://clestonv.github.io/robot_pipeline/report.html

    steps:
      - name: Clonagem Projeto
        uses: actions/checkout@v3

      - name: Configuração do Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Instalar Dependencias do Projeto
        run: |
          pip install robotframework
          pip install robotframework-requests
      
      - name: Execução dos Testes de API
        run: |
          robot -d results tests

      - name: Salvando Resultado dos Testes
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: resultado-testes
          path: ./results

      - name: Configurar Site de Relatorios dos Testes
        uses: actions/configure-pages@v2
        if: always()

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        if: always()
        with:
          path: results/

      - name: Sunir Site de Relatorios dos Testes
        id: deployment
        uses: actions/deploy-pages@v1
        if: always()
    