name: Pipeline Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonagem Projeto
        uses: actions/checkout@v3

      - name: Configuração do Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Instalar Dependencias do Projeto
        run: |
          pip install robotframework
          pip install robotframework-requests
      
      - name: Execução dos Testes de API
        run: |
          robot -d results tests

      - name: Salvando Resultado dos Testes
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: resultado-testes
          path: ./results
    